export const wellKnownLanguages = [
  "English",
  "Japanese",
  "Mandarin Chinese",
  "Cantonese",
  "Irish Gaelic",
  "Yoruba",
  "French",
  "Shona(The Zimbabwean language)",
  "Hindi",
  "Spanish",
  "Standard Arabic",
  "Bengali",
  "Russian",
  "Portuguese",
  "Indonesian",
  "Urdu",
  "German",
  "Swahili",
  "Turkish",
  "Vietnamese",
  "Korean",
  "Italian",
  "Tamil",
  "Thai",
  "Filipino",
  "Dutch",
];
